name: FoodSpoilage
version: @version@
authors: [DanTheTechMan, Undead_Zeratul, Caibinus, Callum, alyphen]
main: spoilagesystem.FoodSpoilage
api-version: 1.13
website: 'https://www.spigotmc.org/resources/food-spoilage.81507/'

commands:
  foodspoilage:
  fs:

permissions:
  fs.help:
    default: true
  fs.timeleft:
    default: true
  fs.reload:
    default: op