name: FoodSpoilage
version: @version@
authors: [DanTheTechMan, Undead_Zeratul, Caibinus, Callum, alyphen]
main: spoilagesystem.FoodSpoilage
api-version: 1.13
website: 'https://www.spigotmc.org/resources/food-spoilage.81507/'
softdepend:
- rpk-food-lib-bukkit
commands:
  foodspoilage:
    aliases: [fs]
    description: |
      Food spoilage base command
      /foodspoilage - displays plugin information
      /foodspoilage help - shows FoodSpoilage commands
      /foodspoilage timeleft - displays the amount of time until the item in your hand expires
      /foodspoilage reload - reloads the config
    usage: /<command> [help|timeleft|reload]
permissions:
  fs.default:
    default: true
  fs.help:
    default: true
  fs.timeleft:
    default: true
  fs.reload:
    default: op